// <auto-generated />
using System;
using MelisaIuliaProiect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MelisaIuliaProiect.Migrations
{
    [DbContext(typeof(MelisaIuliaProiectContext))]
    [Migration("20250101155615_SellerAndEquipment")]
    partial class SellerAndEquipment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MelisaIuliaProiect.Models.Car", b =>
                {
                    b.Property<string>("VIN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Autonomy")
                        .HasColumnType("int");

                    b.Property<string>("CarType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int?>("SellerID")
                        .HasColumnType("int");

                    b.Property<int>("Torque")
                        .HasColumnType("int");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VIN");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("SellerID");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("MelisaIuliaProiect.Models.Equipment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Infotainment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkingAssist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Upholstery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wheels")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("MelisaIuliaProiect.Models.Seller", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Seller");
                });

            modelBuilder.Entity("MelisaIuliaProiect.Models.Car", b =>
                {
                    b.HasOne("MelisaIuliaProiect.Models.Equipment", "Equipment")
                        .WithMany("Cars")
                        .HasForeignKey("EquipmentID");

                    b.HasOne("MelisaIuliaProiect.Models.Seller", "Seller")
                        .WithMany("Cars")
                        .HasForeignKey("SellerID");

                    b.Navigation("Equipment");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("MelisaIuliaProiect.Models.Equipment", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("MelisaIuliaProiect.Models.Seller", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
